/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.cafeteria;

import java.util.ArrayList;
import javax.swing.JOptionPane;


/**
 *
 * @author erasm
 */
public class MenuFrame extends javax.swing.JFrame {
    
    private ArrayList<String> orderNames = new ArrayList<>();
    private ArrayList<Double> orderPrices = new ArrayList<>();
    private ArrayList<Integer> orderQuantities = new ArrayList<>();
    
   
    /**
     * Creates new form MenuFrame
     */
    
    public MenuFrame() {
        initComponents();
        
        setSize(1000, 700);
        setLocationRelativeTo(null);
        setResizable(false);
        jScrollPane1.getVerticalScrollBar().setUnitIncrement(10);
        
    }
    
    private void addToOrder(String name, double price) {
        int index = orderNames.indexOf(name);

        if (index != -1) {
            // item already in the order, add 1 to its quantity
            orderQuantities.set(index, orderQuantities.get(index) + 1);
        } else {
            // new item, add it to all three lists
            orderNames.add(name);
            orderPrices.add(price);
            orderQuantities.add(1);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnPancakes = new javax.swing.JButton();
        btnYogurt = new javax.swing.JButton();
        btnWaffles = new javax.swing.JButton();
        btnBaconEgg = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnPizza = new javax.swing.JButton();
        btnNuggets = new javax.swing.JButton();
        btnBurger = new javax.swing.JButton();
        btnFries = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        Milkshake = new javax.swing.JButton();
        btnPie = new javax.swing.JButton();
        Cheesecake = new javax.swing.JButton();
        btnPudding = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btnCoke = new javax.swing.JButton();
        btnWater = new javax.swing.JButton();
        btnIcedTea = new javax.swing.JButton();
        btnRootbeer = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        btnViewOrder = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(35, 39, 42));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jPanel1.setBackground(new java.awt.Color(35, 39, 42));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Main Meals");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 160, 20));

        jPanel2.setBackground(new java.awt.Color(44, 47, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPancakes.setBackground(new java.awt.Color(114, 137, 218));
        btnPancakes.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnPancakes.setForeground(new java.awt.Color(255, 255, 255));
        btnPancakes.setText("Pancakes");
        btnPancakes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPancakesActionPerformed(evt);
            }
        });
        jPanel2.add(btnPancakes, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 150, 40));

        btnYogurt.setBackground(new java.awt.Color(114, 137, 218));
        btnYogurt.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnYogurt.setForeground(new java.awt.Color(255, 255, 255));
        btnYogurt.setText("Yogurt");
        btnYogurt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYogurtActionPerformed(evt);
            }
        });
        jPanel2.add(btnYogurt, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 40, 150, 40));

        btnWaffles.setBackground(new java.awt.Color(114, 137, 218));
        btnWaffles.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnWaffles.setForeground(new java.awt.Color(255, 255, 255));
        btnWaffles.setText("Waffles");
        btnWaffles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWafflesActionPerformed(evt);
            }
        });
        jPanel2.add(btnWaffles, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 150, 40));

        btnBaconEgg.setBackground(new java.awt.Color(114, 137, 218));
        btnBaconEgg.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnBaconEgg.setForeground(new java.awt.Color(255, 255, 255));
        btnBaconEgg.setText("Bacon & Eggs");
        btnBaconEgg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBaconEggActionPerformed(evt);
            }
        });
        jPanel2.add(btnBaconEgg, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, 150, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 890, 130));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Breakfast Menu");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 160, 20));

        jPanel3.setBackground(new java.awt.Color(44, 47, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPizza.setBackground(new java.awt.Color(114, 137, 218));
        btnPizza.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnPizza.setForeground(new java.awt.Color(255, 255, 255));
        btnPizza.setText("Pizza");
        btnPizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPizzaActionPerformed(evt);
            }
        });
        jPanel3.add(btnPizza, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 150, 40));

        btnNuggets.setBackground(new java.awt.Color(114, 137, 218));
        btnNuggets.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnNuggets.setForeground(new java.awt.Color(255, 255, 255));
        btnNuggets.setText("Chicken Nuggets");
        btnNuggets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuggetsActionPerformed(evt);
            }
        });
        jPanel3.add(btnNuggets, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 40, 150, 40));

        btnBurger.setBackground(new java.awt.Color(114, 137, 218));
        btnBurger.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnBurger.setForeground(new java.awt.Color(255, 255, 255));
        btnBurger.setText("Cheeseburger");
        btnBurger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBurgerActionPerformed(evt);
            }
        });
        jPanel3.add(btnBurger, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 150, 40));

        btnFries.setBackground(new java.awt.Color(114, 137, 218));
        btnFries.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnFries.setForeground(new java.awt.Color(255, 255, 255));
        btnFries.setText("Fries");
        btnFries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFriesActionPerformed(evt);
            }
        });
        jPanel3.add(btnFries, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 40, 150, 40));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 890, 120));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Desserts");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 160, 20));

        jPanel4.setBackground(new java.awt.Color(44, 47, 51));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Milkshake.setBackground(new java.awt.Color(114, 137, 218));
        Milkshake.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Milkshake.setForeground(new java.awt.Color(255, 255, 255));
        Milkshake.setText("Milkshake");
        Milkshake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MilkshakeActionPerformed(evt);
            }
        });
        jPanel4.add(Milkshake, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 150, 40));

        btnPie.setBackground(new java.awt.Color(114, 137, 218));
        btnPie.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnPie.setForeground(new java.awt.Color(255, 255, 255));
        btnPie.setText("Blueberry Pie");
        btnPie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPieActionPerformed(evt);
            }
        });
        jPanel4.add(btnPie, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 40, 150, 40));

        Cheesecake.setBackground(new java.awt.Color(114, 137, 218));
        Cheesecake.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Cheesecake.setForeground(new java.awt.Color(255, 255, 255));
        Cheesecake.setText("Cheesecake");
        Cheesecake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheesecakeActionPerformed(evt);
            }
        });
        jPanel4.add(Cheesecake, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 150, 40));

        btnPudding.setBackground(new java.awt.Color(114, 137, 218));
        btnPudding.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnPudding.setForeground(new java.awt.Color(255, 255, 255));
        btnPudding.setText("Pudding");
        btnPudding.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPuddingActionPerformed(evt);
            }
        });
        jPanel4.add(btnPudding, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 40, 150, 40));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, 890, 120));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Drinks");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 580, 160, 20));

        jPanel5.setBackground(new java.awt.Color(44, 47, 51));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCoke.setBackground(new java.awt.Color(114, 137, 218));
        btnCoke.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnCoke.setForeground(new java.awt.Color(255, 255, 255));
        btnCoke.setText("Coke");
        btnCoke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCokeActionPerformed(evt);
            }
        });
        jPanel5.add(btnCoke, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 150, 40));

        btnWater.setBackground(new java.awt.Color(114, 137, 218));
        btnWater.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnWater.setForeground(new java.awt.Color(255, 255, 255));
        btnWater.setText("Water");
        btnWater.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWaterActionPerformed(evt);
            }
        });
        jPanel5.add(btnWater, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 40, 150, 40));

        btnIcedTea.setBackground(new java.awt.Color(114, 137, 218));
        btnIcedTea.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnIcedTea.setForeground(new java.awt.Color(255, 255, 255));
        btnIcedTea.setText("Iced Tea");
        btnIcedTea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIcedTeaActionPerformed(evt);
            }
        });
        jPanel5.add(btnIcedTea, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 150, 40));

        btnRootbeer.setBackground(new java.awt.Color(114, 137, 218));
        btnRootbeer.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnRootbeer.setForeground(new java.awt.Color(255, 255, 255));
        btnRootbeer.setText("Rootbeer");
        btnRootbeer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRootbeerActionPerformed(evt);
            }
        });
        jPanel5.add(btnRootbeer, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 40, 150, 40));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 610, 890, 140));

        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 540));

        jPanel6.setBackground(new java.awt.Color(44, 47, 51));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnViewOrder.setBackground(new java.awt.Color(114, 137, 218));
        btnViewOrder.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnViewOrder.setForeground(new java.awt.Color(255, 255, 255));
        btnViewOrder.setText("View Order");
        btnViewOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewOrderActionPerformed(evt);
            }
        });
        jPanel6.add(btnViewOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 750, 40));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 550, 1000, 140));

        jSeparator1.setBackground(new java.awt.Color(153, 170, 181));
        jSeparator1.setForeground(new java.awt.Color(153, 170, 181));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, 1000, 10));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnYogurtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYogurtActionPerformed
        // TODO add your handling code here:
        addToOrder("Yogurt", 69.00);
        JOptionPane.showMessageDialog(null, "Order Added");
    }//GEN-LAST:event_btnYogurtActionPerformed

    private void btnNuggetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuggetsActionPerformed
        // TODO add your handling code here:
        addToOrder("Chicken Nuggets", 89.00);
        JOptionPane.showMessageDialog(null, "Order Added");
    }//GEN-LAST:event_btnNuggetsActionPerformed

    private void btnPieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPieActionPerformed
        // TODO add your handling code here:
        addToOrder("Blueberry Pie", 76.00);
        JOptionPane.showMessageDialog(null, "Order Added");
    }//GEN-LAST:event_btnPieActionPerformed

    private void btnWaterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWaterActionPerformed
        // TODO add your handling code here:
        addToOrder("Water", 25.00);
        JOptionPane.showMessageDialog(null, "Order Added");
    }//GEN-LAST:event_btnWaterActionPerformed

    private void btnPancakesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPancakesActionPerformed
        // TODO add your handling code here:
        addToOrder("Pancakes", 99.00);
        JOptionPane.showMessageDialog(null, "Order Added");
    }//GEN-LAST:event_btnPancakesActionPerformed

    private void btnWafflesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWafflesActionPerformed
        // TODO add your handling code here:
        addToOrder("Waffles", 99.00);
        JOptionPane.showMessageDialog(null, "Order Added");
    }//GEN-LAST:event_btnWafflesActionPerformed

    private void btnBaconEggActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBaconEggActionPerformed
        // TODO add your handling code here:
        addToOrder("Bacon and Eggs", 130.00);
        JOptionPane.showMessageDialog(null, "Order Added");
    }//GEN-LAST:event_btnBaconEggActionPerformed

    private void btnPizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPizzaActionPerformed
        // TODO add your handling code here:
        addToOrder("Pizza", 260.00);
        JOptionPane.showMessageDialog(null, "Order Added");
    }//GEN-LAST:event_btnPizzaActionPerformed

    private void btnBurgerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBurgerActionPerformed
        // TODO add your handling code here:
        addToOrder("Cheeseburger", 120.00);
        JOptionPane.showMessageDialog(null, "Order Added");
    }//GEN-LAST:event_btnBurgerActionPerformed

    private void btnFriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFriesActionPerformed
        // TODO add your handling code here:
        addToOrder("Fries", 65.00);
        JOptionPane.showMessageDialog(null, "Order Added");
    }//GEN-LAST:event_btnFriesActionPerformed

    private void MilkshakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MilkshakeActionPerformed
        // TODO add your handling code here:
        addToOrder("Milkshake", 79.00);
        JOptionPane.showMessageDialog(null, "Order Added");
    }//GEN-LAST:event_MilkshakeActionPerformed

    private void CheesecakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheesecakeActionPerformed
        // TODO add your handling code here:
        addToOrder("Cheesecake", 129.00);
        JOptionPane.showMessageDialog(null, "Order Added");
    }//GEN-LAST:event_CheesecakeActionPerformed

    private void btnPuddingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPuddingActionPerformed
        // TODO add your handling code here:
        addToOrder("Pudding", 69.00);
        JOptionPane.showMessageDialog(null, "Order Added");
    }//GEN-LAST:event_btnPuddingActionPerformed

    private void btnCokeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCokeActionPerformed
        // TODO add your handling code here:
        addToOrder("Coke", 50.00);
        JOptionPane.showMessageDialog(null, "Order Added");
    }//GEN-LAST:event_btnCokeActionPerformed

    private void btnIcedTeaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIcedTeaActionPerformed
        // TODO add your handling code here:
        addToOrder("Iced Tea", 30.00);
        JOptionPane.showMessageDialog(null, "Order Added");
    }//GEN-LAST:event_btnIcedTeaActionPerformed

    private void btnRootbeerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRootbeerActionPerformed
        // TODO add your handling code here:
        addToOrder("Rootbeer", 50.00);
        JOptionPane.showMessageDialog(null, "Order Added");
    }//GEN-LAST:event_btnRootbeerActionPerformed

    private void btnViewOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewOrderActionPerformed
        // TODO add your handling code here:
        new ViewOrder(orderNames, orderPrices, orderQuantities).setVisible(true);
    }//GEN-LAST:event_btnViewOrderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cheesecake;
    private javax.swing.JButton Milkshake;
    private javax.swing.JButton btnBaconEgg;
    private javax.swing.JButton btnBurger;
    private javax.swing.JButton btnCoke;
    private javax.swing.JButton btnFries;
    private javax.swing.JButton btnIcedTea;
    private javax.swing.JButton btnNuggets;
    private javax.swing.JButton btnPancakes;
    private javax.swing.JButton btnPie;
    private javax.swing.JButton btnPizza;
    private javax.swing.JButton btnPudding;
    private javax.swing.JButton btnRootbeer;
    private javax.swing.JButton btnViewOrder;
    private javax.swing.JButton btnWaffles;
    private javax.swing.JButton btnWater;
    private javax.swing.JButton btnYogurt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
