/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.cafeteria;

import java.util.ArrayList;

public class ReceiptFrame extends javax.swing.JFrame {

    private ArrayList<String> orderNames;
    private ArrayList<Double> orderPrices;
    private ArrayList<Integer> orderQuantities;
    private double cashGiven;

    /**
     * Creates new form ReceiptFrame
     */
    public ReceiptFrame(ArrayList<String> names,
                        ArrayList<Double> prices,
                        ArrayList<Integer> quantities,
                        double cash) {

        initComponents();

        setSize(420, 580);
        setLocationRelativeTo(null);
        setResizable(false);

        orderNames = names;
        orderPrices = prices;
        orderQuantities = quantities;
        cashGiven = cash;

        txtAreaReceipt.setEditable(false);

        buildReceipt();
    }

    private void buildReceipt() {

        double subtotal = 0;
        StringBuilder sb = new StringBuilder();

        sb.append("-------------- RECEIPT --------------\n\n");

        for (int i = 0; i < orderNames.size(); i++) {

            double lineTotal =
                    orderPrices.get(i) * orderQuantities.get(i);

            subtotal += lineTotal;

            sb.append(String.format(
                    "%-15s x%-3d ₱%.2f\n",
                    orderNames.get(i),
                    orderQuantities.get(i),
                    lineTotal
            ));
        }

        double tax = subtotal * 0.12;
        double total = subtotal + tax;
        double change = cashGiven - total;

        sb.append("\n-------------------------------\n");
        sb.append(String.format("Subtotal: ₱%.2f\n", subtotal));
        sb.append(String.format("VAT (12%%): ₱%.2f\n", tax));
        sb.append(String.format("Total: ₱%.2f\n", total));
        sb.append(String.format("Cash: ₱%.2f\n", cashGiven));
        sb.append(String.format("Change: ₱%.2f\n", change));

        txtAreaReceipt.setText(sb.toString());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaReceipt = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(35, 39, 42));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtAreaReceipt.setColumns(20);
        txtAreaReceipt.setRows(5);
        jScrollPane1.setViewportView(txtAreaReceipt);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 340, 520));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 780));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtAreaReceipt;
    // End of variables declaration//GEN-END:variables
}