/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.cafeteria;

import java.util.ArrayList;
import javax.swing.DefaultListModel;

/**
 *
 * @author erasm
 */
public class ViewOrder extends javax.swing.JFrame {

    /**
     * Creates new form ViewOrder
     */
    private ArrayList<String> orderNames;
    private ArrayList<Double> orderPrices;
    private ArrayList<Integer> orderQuantities;
    private DefaultListModel<String> listModel = new DefaultListModel<>();
    
    public ViewOrder(ArrayList<String> names, ArrayList<Double> prices, ArrayList<Integer> quantities) {
        initComponents();
        setSize(570, 570);
        setLocationRelativeTo(null);
        setResizable(false);
        
        orderNames = names;
        orderPrices = prices;
        orderQuantities = quantities;
        
        lstOrder.setModel(listModel);
        displayOrder();
        
    }
    private void displayOrder() {
    listModel.clear();
    double total = 0;

        for (int i = 0; i < orderNames.size(); i++) {
            listModel.addElement(orderNames.get(i) + " x" + orderQuantities.get(i));
            total += orderPrices.get(i) * orderQuantities.get(i);
        }

        lblTotal.setText(String.format("Total: ₱%.2f", total));
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstOrder = new javax.swing.JList<>();
        lblTotal = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnCheckout = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(35, 39, 42));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lstOrder.setBackground(new java.awt.Color(44, 47, 51));
        lstOrder.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lstOrder.setForeground(new java.awt.Color(255, 255, 255));
        lstOrder.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lstOrder);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 490, 340));

        lblTotal.setBackground(new java.awt.Color(44, 47, 51));
        lblTotal.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(255, 255, 255));
        lblTotal.setText("Total: ");
        jPanel1.add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 190, 40));

        btnBack.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnBack.setText("Go Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, 480, 30));

        btnCheckout.setBackground(new java.awt.Color(114, 137, 218));
        btnCheckout.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnCheckout.setForeground(new java.awt.Color(255, 255, 255));
        btnCheckout.setText("Proceed To Checkout");
        btnCheckout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckoutActionPerformed(evt);
            }
        });
        jPanel1.add(btnCheckout, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, 350, 40));

        btnRemove.setBackground(new java.awt.Color(114, 137, 218));
        btnRemove.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnRemove.setForeground(new java.awt.Color(255, 255, 255));
        btnRemove.setText("Remove");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });
        jPanel1.add(btnRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 440, 110, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        this.dispose();
        
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnCheckoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckoutActionPerformed
            // TODO add your handling code here:
        if (orderNames.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Your order is empty. Please add at least one item before checking out.");
        return;
        }

 
        double subtotal = 0;
        for (int i = 0; i < orderNames.size(); i++) {
            subtotal += orderPrices.get(i) * orderQuantities.get(i);
        }
        double totalWithTax = subtotal * 1.12;

  
        String input = javax.swing.JOptionPane.showInputDialog(this,
                String.format("Total: ₱%.2f\nEnter cash amount:", totalWithTax));

        if (input == null) {
            return; 
        }

        double cash;
        try {
            cash = Double.parseDouble(input.trim());
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please enter a valid number.");
            return;
        }

        if (cash < totalWithTax) {
            javax.swing.JOptionPane.showMessageDialog(this, "Cash is not enough for the total amount.");
            return;
        }

        new ReceiptFrame(orderNames, orderPrices, orderQuantities, cash).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCheckoutActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        // TODO add your handling code here:
        int index = lstOrder.getSelectedIndex();

        if (index == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Select an item to remove first.");
            return;
        }

        orderNames.remove(index);
        orderPrices.remove(index);
        orderQuantities.remove(index);
        displayOrder();
    }//GEN-LAST:event_btnRemoveActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCheckout;
    private javax.swing.JButton btnRemove;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JList<String> lstOrder;
    // End of variables declaration//GEN-END:variables
}
